on:
  push:
    branches:
      - develop
      - feature/*
      - release/*

name: Deploy to Develop/Staging (us-east-1)

jobs:
  deploy:
    name: Deploy Lambda to AWS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Filter only modified Functions
      uses: dorny/paths-filter@v2.2.1
      id: filter
      with:
        filters: .github/filters.yml

    - name: Deploy to AWS
      uses: blombard/lambda-monorepo@master
      with:
        lambda-functions: '${{ toJson(steps.filter.outputs) }}'
        zip-params: '*.js *.json *.js.map node_modules/'
        # alias-name: 'production'
        # layer-name: 'MyLayer'
